version: "2.3"
services:
  emby:
      network_mode: bridge
      ports:
          - '8096:8096'
          #- '8920:8920'
          #- '1900:1900/udp'
          #- '7359:7359/udp'
      volumes:
          - ./config:/config
          - ./tvshows:/tvshows
          - ./movies:/movies
          #- ./downloads/:/data
      environment:
          - TZ=Asia/Shanghai
          - UID=0
          - GID=0
          - GIDLIST=0
          #- 'HTTP_PROXY=http://你的代理IP:你的代理端口/'
          #- 'HTTPS_PROXY=http://你的代理IP:你的代理端口/'
      #devices:
      #    - /dev/dri:/dev/dri 
      restart: always
      container_name: embyserver
      image: lovechen/embyserver


